---
abstract: 'Plack application for SOAP::WSDL Server modules'
author:
  - 'Andreas Stricker <andy@knitter.ch>'
build_requires:
  Plack::Test: 0
  Test::Class: 0
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300025, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SOAP-WSDL-Server-Plack
requires:
  HTTP::Headers: 0
  HTTP::Request: 0
  Moose: 0
  MooseX::FollowPBP: 0
  Plack::Request: 0
  Plack::Util: 0
  SOAP::WSDL: 0
  Try::Tiny: 0
  namespace::autoclean: 0
version: 0.006
